version: "3.8"
services:
  jenkins:
    image: jenkins-server:1.0
    user: root
    ports:
      - "8082:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-home:/home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - registry:/var/lib/registry
    restart: always
  sonarqube:
    image: sonarqube:8.5.0-community
    ports:
      - "9000:9000"
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions
    restart: always
volumes:
  jenkins-data:
  jenkins-home:
  registry:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions:
